# # # # # # # # # # # # # # # # # # #
#                                   #
# Thanks for use Snake's UHC-Meetup #
#                                   #
# # # # # # # # # # # # # # # # # # #


# Next feature :)
Mode: meetup

# Lobby like MineHQ?
Lobby:
  enabled: true

# Border Config
Border:
  # Default Size.
  Default: 120
  # Moved border tasks to Extra/Border.yml

# Game Options, Max players, Min players, etc..
GameOptions:
  MinPlayers: 12
  MaxPlayers: 16
  RestartCommand: 'stop'
  Lobby: 'hub'
  # Vote time..
  VoteTime: 30
  # Starting time
  StartingTime: 15
  # End Time
  EndTime: 15
  GAppleName: '&6Golden Head'
  CustomKit: false
TeleportOptions:
  # This value is a double, please put the .0
  # Wrong: 20
  # Fine: 20.0
  MinDistance: 20.0