# Types: MongoDB, MySQL, NONE
DatabaseType: NONE
MongoDB:
  ips: 127.0.0.1,127.0.0.2
  user: admin
  pass: admin123
MySQL:
  driver-class: 'com.mysql.jdbc.Driver'
  jdbc-url: 'jdbc:mysql://<host>:<port>/<database>'
  hostname: '127.0.0.1'
  port: '3306'
  database: 'UHCMeetup'
  username: 'root'
  password: 'password'
  checkout-timeout: 5000