ScoreBoard:
    Title: '&6&lUHC Meetup'
    Lines:
      - '&7&m-------------------'
      - '&6&lJugadores:&f %online%'
      - '&6&lEspectadores:&f %specs%'
      - ''
      - '&2&lTus Kills:&f %kills%'
      - ''
      - '&a&lBorde:&f %border%'
      - '&a&lSe achica en:&f %time%'
      - ''
      - '&e&l@MicPixel'
      - '&7&m-------------------'
Lobby: Hub
MaxPlayers: 16
MinPlayers: 6
MinVotes: 2
StartMSG: '&8[&aUHCMeetup&8]&6 Starting in &e%time%s'
StartedMSG: '&8[&aUHCMeetup&8]&6 Good lock!'
Border: '&8[&aUHCMeetup&8]&6 Border shrinking to &e%coords% &6in &e%time%s'
BorderNow: '&8[&aUHCMeetup&8]&6 Border is now at &e%coords%'
NextUpdate: '&cThis function will be coming soon'
WinMSG: '&8[&aUHCMeetup&8]&a %player%&6 has win the UHCMeetup'
MlgMSG: '&8[&aUHCMeetup&8]&e Use &a/mlg&e to test yourself in the Waterdrop'
Items:
  Hub: '&aLeave'
  Options: '&aOptions'
  Players: '&aPlayers'
  Vote: '&aVote for start'