#Don't touch. This options is for a kits, internal code. Check: 
Kits: 0
## ScoreBoard :)
ScoreBoard:
    Title: '&6&lUHC Meetup'
    Lines:
      - '&7&m-------------------'
      - '&6&lJugadores:&f %online%'
      - '&6&lEspectadores:&f %specs%'
      - ''
      - '&2&lTus Kills:&f %kills%'
      - ''
      - '&a&lBorde:&f %border%'
      - '&a&lSe achica en:&f %time%'
      - ''
      - '&e&l@MicPixel'
      - '&7&m-------------------'
## Lobby server
Lobby: Hub
MaxPlayers: 16
MinPlayers: 6
MinVotes: 2
VotesMSG: '&8[&aUHCMeetup&8]&6 Need &a%votes%&6 more votes for start game'
GameFull: '&cGame Full'
GameStarted: '&cGame started'
StartMSG: '&8[&aUHCMeetup&8]&6 Starting in &e%time%s'
StartedMSG: '&8[&aUHCMeetup&8]&6 Good lock!'
Restarting: '&8[&aUHCMeetup&8]&6 Game restarting in &e%time%s'
Border: '&8[&aUHCMeetup&8]&6 Border shrinking to &e%coords% &6in &e%time%s'
BorderNow: '&8[&aUHCMeetup&8]&6 Border is now at &e%coords%'
NextUpdate: '&cThis function will be coming soon'
WinMSG: '&8[&aUHCMeetup&8]&a %player%&6 has win the UHCMeetup'
MlgMSG: '&8[&aUHCMeetup&8]&e Use &a/mlg&e to test yourself in the Waterdrop'
QuitMessage: '&8[&aUHCMeetup&8] &a%player%&e has quit&6. &a%online%&7/&a%max%'
JoinMessage: '&8[&aUHCMeetup&8] &a%player%&e has joined&6. &a%online%&7/&a%max%'
MenuName: '&aPlayers:'
OptionsMenu: '&aOptions'
Chats:
  Alive: true
  AliveFormat: '&e%player%&f:&7 '
  Spect: true
  SpectFormat: '&b[Spec] &e%player%&f:&7 '
Items:
  Hub: '&aLeave'
  Options: '&aOptions'
  Players: '&aPlayers'
  Vote: '&aVote for start'
  BorderI: '&aBorder in 1.8?'
  Border:
    Enable:
      - '&eFeature enabled'
    Disable:
      - '&cFeature disabled'